Main:
  defaultLocale: english
  availableLocale:
  - english
  - french
  - portuguese

Auction:
  enabled: true
  allowCreative: false
  displayRenamed: false
  cooldown: 60
  minStart: 100
  maxStart: 100000

  Queue:
    maxSize: 10
    maxPerPlayer: 10

  taxAccount: None
  useTaxAccount: false
  startTax: 0
  endTax: 0
  startTaxIsPercent: false
  endTaxIsPercent: true
  taxIfNoBids: false
  
  notifyTime:
  - 30
  - 10
  - 5

  WorldGroups:
    groups:
    - groupName: default
      enabled: true
      worlds: [world, world_the_end, world_nether]
      channels: []

  WorldGuardRegions:
    enabled: false
    defaultToStash: true
    defaultDeny: [start, cancel, end, collect]
    regions:
    - regionName: [spawn]
      enabled: true
      toStash: false
      deny: [none]


  
  Blacklist:
  - Bedrock
  - Dirt
  - Cobblestone
  - Ender Pearl
  
  Bidding:
    minIncrement: 100
    maxIncrement: 10000
    defaultTime: 60
    minTime: 30
    maxTime: 120
    snipeTime: 10
    snipeValue: 10
    