Main:
  defaultLocale: english
  availableLocale:
  - english
  
Auction:
  enabled: true
  allowCreative: false
  cooldown: 300
  minStart: 100
  maxStart: 100000
  
  notifyTime:
  - 30
  - 10
  - 5
  
  Blacklist:
  - Bedrock
  - Dirt
  - Cobblestone
  
  Bidding:
    minIncrement: 100
    maxIncrement: 10000
    defaultTime: 60
    snipeTime: 10
    snipeValue: 10
    