Main:
  defaultLocale: english
  availableLocale:
  - english
  - french
  - portuguese
  
Auction:
  enabled: true
  allowCreative: false
  cooldown: 300
  minStart: 100
  maxStart: 100000

  Queue:
    maxSize: 1
    maxPerPlayer: 1


  
  taxAccount: None
  useTaxAccount: false
  startTax: 0
  endTax: 0
  startTaxIsPercent: false
  endTaxIsPercent: true
  taxIfNoBids: false
  
  notifyTime:
  - 30
  - 10
  - 5
  
  Blacklist:
  - Bedrock
  - Dirt
  - Cobblestone
  - Ender Pearl
  
  Bidding:
    minIncrement: 100
    maxIncrement: 10000
    defaultTime: 60
    snipeTime: 10
    snipeValue: 10
    