Main:
  defaultLocale: english
  availableLocale:
  - english
  
Auction:
  allowCreative: false
  cooldown: 300
  maxTime: 300
  minStart: 100
  maxStart: 100000
  
  notifyTime:
  - 30
  - 10
  - 5
  - 4
  - 3
  - 2
  - 1
  
  Blacklist:
  - Bedrock
  - Dirt
  
  Bidding:
    minIncrement: 100
    maxIncrement: 10000
    defaultTime: 60
    snipeTime: 10
    snipeValue: 5
    
  Logging:
    enabled: true
    filename: log.yml
    type: yaml
    mysqlHost: localhost
    mysqlPort: 3306
    mysqlUsername: USERNAME
    mysqlPassword: PASSWORD
    mysqlDatabase: minecraft
    mysqlTable: salesmania_log