name: Salesmania
version: 1.34
description: Plugin for handling player auctions.
author: Justin
authors: [Khaos_Fury]
website: http://invisioncraft.net
main: net.invisioncraft.plugins.salesmania.Salesmania
depend: [Vault]
softdepend: [TownyChat, Herochat]

commands:
  auction:
    description: Salesmania auction
  salesmania:
    description: Salesmania
  bid:
    description: Bid on an auction
  collect:
    description: Collect items from stash
    
permissions:
  salesmania.*:
    description: Access to all salesmania commands
    default: op
    children:
      salesmania.auction.*: true
      salesmania.admin.*: true   
  salesmania.auction.*:
    description: Access to all salesmania auction commands
    default: op
    children:
      salesmania.auction.start: true
      salesmania.auction.bid: true
  salesmania.admin.*:
    description: Access to all salesmania commands
    default: op
    children:
      salesmania.admin.reload: true
      salesmania.auction.cancel: true
      salesmania.auction.end: true
      salesmania.auction.enable: true
      salesmania.auction.disable: true
  salesmania.auction.start:
    description: Allows you to start an auction.
    default: op
  salesmania.auction.bid:
    description: Allows you to bid on an auction.
    default: op
  salesmania.auction.cancel:
    description: Allows you to cancel ANY auction.
    default: op
  salesmania.auction.end:
    description: Allows you to end ANY auction.
    default: op
  salesmania.auction.enable:
    description: Allows you to enable the auction.
    default: op
  salesmania.auction.disable:
    description: Allows you to disable the auction.
    default: op
  salesmania.admin.reload:
    description: Allows you to reload salesmania configuration
    default: op
  
  