name: Salesmania
version: 0.1a
description: Plugin for handling player auctions.
author: Justin
authors: [Khaos_Fury]
website: http://invisioncraft.net
main: net.invisioncraft.plugins.salesmania.Salesmania
softdepend: [Vault]

commands:
  auction:
    description: Salesmania auction
    permission: salesmania.auction
  salesmania:
    description: Salesmania
    permission: salesmania.admin
  permissions:
    salesmania.*:
      description: Access to all salesmania commands
      default: op
      children:
        salesmania.auction.*: true
        salesmania.admin: true
        
    salesmania.auction.*:
      description: Access to all salesmania auction commands
      default: op
      children:
        salesmania.auction.start: true
    salesmania.admin.*:
      description: Provides access salesmania admin commands
      default: op
      children:
        salesmania.admin.reload: true
        salesmania.auction.cancel: true
        salesmania.auction.end: true
        salesmania.auction.enable: true
        salesmania.auction.disable: true
    