name: Salesmania
version: 0.1a
description: Plugin for handling player auctions.
author: Justin
authors: [Khaos_Fury]
website: http://invisioncraft.net

main: net.invisioncraft.plugins.salesmania.Salesmania
softdepend: [Vault]